# Generated by Django 5.2.7 on 2025-11-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='subtitle',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banners',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
