# Generated by Django 5.2.7 on 2025-11-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_magazine'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='image',
            field=models.ImageField(default=1, upload_to='magazines/'),
            preserve_default=False,
        ),
    ]
