# Generated by Django 5.2.7 on 2025-11-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_award'),
    ]

    operations = [
        migrations.RenameField(
            model_name='magazine',
            old_name='magazine_pdf',
            new_name='magazine_link',
        ),
    ]
