# Generated by Django 5.2.7 on 2025-11-06 06:43

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_rename_magazine_pdf_magazine_magazine_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='description',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
