# Generated by Django 5.2.7 on 2025-11-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_award_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AwardImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='award_images/')),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_images', to='web.award')),
            ],
            options={
                'verbose_name': 'Award Image',
                'verbose_name_plural': 'Award Images',
            },
        ),
    ]
