# Generated by Django 5.2.7 on 2025-11-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_award_slug_awardimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='images',
            new_name='image',
        ),
    ]
