# Generated by Django 5.2.7 on 2025-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_event_date_remove_event_time_event_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='auther',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='auther_image',
        ),
        migrations.AddField(
            model_name='event',
            name='author_image',
            field=models.ImageField(default=1, upload_to='event_authors/'),
            preserve_default=False,
        ),
    ]
