# Generated by Django 5.2.7 on 2025-11-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_rename_auther_event_author_remove_event_auther_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BixjiTalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_link', models.URLField(help_text='Link to the Bixji Talk video (e.g., YouTube link)')),
            ],
            options={
                'verbose_name': 'Bixji Talk',
                'verbose_name_plural': 'Bixji Talks',
            },
        ),
    ]
