# Generated by Django 5.2.7 on 2025-11-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_bixjitalk'),
    ]

    operations = [
        migrations.AddField(
            model_name='bixjitalk',
            name='image',
            field=models.ImageField(default=1, upload_to='bixji_talks/'),
            preserve_default=False,
        ),
    ]
