# Generated by Django 5.2.7 on 2025-11-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_clubregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.award')),
            ],
            options={
                'verbose_name': 'Award Nomination',
                'verbose_name_plural': 'Award Nominations',
            },
        ),
    ]
