# Generated by Django 5.2.7 on 2025-11-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_awardnomination'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AwardImages',
            new_name='AwardGallery',
        ),
        migrations.AlterModelOptions(
            name='awardgallery',
            options={'verbose_name': 'Award Gallery', 'verbose_name_plural': 'Award Galleries'},
        ),
    ]
