# Generated by Django 5.2.7 on 2025-11-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_rename_awardimages_awardgallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BixjiTalkEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('social_link', models.TextField()),
                ('short_video_link', models.URLField(help_text='Link to the short video (e.g., YouTube, Instagram link)')),
            ],
            options={
                'verbose_name': 'Bixji Talk Enquiry',
                'verbose_name_plural': 'Bixji Talk Enquiries',
            },
        ),
    ]
