# Generated by Django 5.2.7 on 2025-11-10 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_bixjitalkenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='bixjitalkenquiry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
