# Generated by Django 5.2.7 on 2025-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0026_alter_faq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('bixji_talks', 'Bixji Talks'), ('magazines', 'Magazines'), ('awards', 'Awards'), ('awards_gallery', 'Awards Gallery'), ('clubs', 'Clubs'), ('events', 'Events'), ('event_gallery', 'Event Gallery'), ('contact', 'Contact')], max_length=180)),
                ('meta_title', models.CharField(max_length=180)),
                ('meta_keywords', models.CharField(max_length=200)),
                ('meta_description', models.CharField(max_length=180)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meta/')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='award',
            name='meta_description',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='meta_description',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
